baseURL = "https://wangzh-hao.github.io/"
locale = "zh-cn"
title = "Wangzh"

theme = "AllinOne"

builddrafts = false
canonifyurls = true
enableEmoji = true
hasCJKLanguage = true
summaryLength = 200
Paginate = 3

[permalinks]
  blog = "blog/:year-:month/:slug/"

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[menu]
  [[menu.main]]
    name = "Blog"
    weight = -120
    identifier = "blog"
    url = "blog/"

  [[menu.main]]
    name = "Thinking"
    weight = -115
    identifier = "thinking"
    url = "thinking/"

  [[menu.main]]
    name = "About"
    weight = -110
    identifier = "about"
    url = "about/"

[params]
  author = "Wangzh"
  description = "Web Front-end Developer. 佛系拖延症患者."
  avatar = "img/profile.jpg"
  faviconfile = "img/profile.jpg"
  welcome_head = "Hello, World!"
  welcome_word = "~ 浮云游子意 落日故人情 ~"
  latestpostscount = 5
  bloggroupby = 'month'
  dateform = "Jan 2, 2006"
  dateformfull = "2006-01-02  Monday  15:04:05"
  noshowreadtime = false

  # social links
  weibo = "//weibo.com/u/1929957130"
  github = "//github.com/Wangzh-Hao"
  instagram = "//instagram.com/wangzhihaooo"
  email = "zhihaowang_wzh@163.com"

  # slides
  slidesDirPath = "themes/AllinOne/static/img/header-slides"
  slidesDirPathURL = "img/header-slides"

  # highlighting
  highlightjs = true

  # latex
  katex = true

  include_rss = true
