baseURL = "https://wangzh-hao.github.io/"
title = "Wangzh"

theme = "AllinOne"

builddrafts = false
canonifyurls = true
enableEmoji = true
hasCJKLanguage = true
summaryLength = 200
Paginate = 3

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[permalinks]
  blog = "blog/:year-:month/:slug/"

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[languages]
  [languages.en]
    locale = "en"
    label = "English"
    weight = 1
    contentDir = "content"
    [languages.en.params]
      author = "Wangzh"
      description = "Web Developer"
      welcome_head = "Hello, World!"
      welcome_word = "~ Travelers are like floating clouds, old friends are like the setting sun ~"

  [languages.zh]
    locale = "zh-cn"
    label = "中文"
    weight = 2
    contentDir = "content/zh"
    [languages.zh.params]
      author = "Wangzh"
      description = "Web Front-end Developer. 佛系拖延症患者."
      welcome_head = "Hello, World!"
      welcome_word = "~ 浮云游子意 落日故人情 ~"

[params]
  i18n_flags = true
  avatar = "img/profile.jpg"
  faviconfile = "img/profile.jpg"
  latestpostscount = 5
  bloggroupby = 'month'
  dateform = "Jan 2, 2006"
  dateformfull = "2006-01-02  Monday  15:04:05"
  noshowreadtime = false

  # social links
  weibo = "//weibo.com/u/1929957130"
  github = "//github.com/Wangzh-Hao"

  # slides
  slidesDirPath = "themes/AllinOne/static/img/header-slides"
  slidesDirPathURL = "img/header-slides"

  # highlighting
  highlightjs = true

  # latex
  katex = true

  include_rss = true

[menu]
  [[menu.main]]
    name = "Blog"
    weight = -120
    identifier = "blog"
    url = "blog/"

  [[menu.main]]
    name = "Thinking"
    weight = -115
    identifier = "thinking"
    url = "thinking/"

  [[menu.main]]
    name = "About"
    weight = -110
    identifier = "about"
    url = "about/"
